version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ${FOLDER_LOCATION}:/usr/share/nginx/html:ro
    restart: always
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
      VIRTUAL_PORT: 80
    networks:
      - proxy

networks:
  proxy:
    external:
      name: nginx-proxy
