version: '3'

services:
  bash:
    image: bash:latest
    volumes:
      - data:/data
      - ./entrypoint.sh:/entrypoint.sh:ro
    environment:
      FOLDER_LOCATION: ${FOLDER_LOCATION}
    command: bash /entrypoint.sh

  nginx:
    image: nginx:latest
    volumes:
      - data:/usr/share/nginx/html:ro
    restart: always
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
      VIRTUAL_PORT: 80
    networks:
      - proxy

volumes:
  data:
networks:
  proxy:
    external:
      name: nginx-proxy
