version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - default

  wordpress:
    image: wordpress:latest
    volumes:
      - wordpress:/var/www/html
      - /root/wordpress_custom_php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    ports:
      - 80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      VIRTUAL_HOST: ${HOSTNAME}
      LETSENCRYPT_HOST: ${HOSTNAME}
      VIRTUAL_PORT: 80
    networks:
      - proxy
      - default

volumes:
  database:
  wordpress:

networks:
  proxy:
    external:
      name: nginx-proxy
